name: macros_demo
version: "0.1"

vars:
  # used by macros and examples
  default_country: "DE"

models: {}

seeds: {}

tests:
  - type: not_null
    table: dim_users
    column: user_id
    tags: [batch]
  - type: row_count_between
    table: fct_user_sales
    min_rows: 1
    tags: [batch]
