# My Local Playground
dev_duckdb:
  engine: duckdb
  duckdb:
    path: ".local/dev.duckdb"

# My Local utest Overrides
dev_duckdb_utest:
  engine: duckdb
  duckdb:
    path: ":memory:"

# My Production Environment
prod_bigquery:
  engine: bigquery
  bigquery:
    project: "fft-basic-demo"
    dataset: "production_marts"
    location: "EU"
    # Use the pandas backend here; FFT can also use BigFrames if you set this to true.
    use_bigframes: false
    allow_create_dataset: true

# My Production utest Overrides
prod_bigquery_utest:
  engine: bigquery
  bigquery:
    dataset: "production_marts_utest"
