# My Local Playground
dev_duckdb:
  engine: duckdb
  duckdb:
    path: ".local/dev.duckdb"

# My Production Environment
prod_bigquery:
  engine: bigquery
  bigquery:
    project: "basic_data"
    dataset: "production_marts"
    location: "EU"
    # FFT handles the client (BigFrames or Pandas) automatically
    use_bigframes: true
    allow_create_dataset: true