# Source declarations describe external tables. See docs/Sources.md for details.
version: 2
# sources:
  # Example:
  # - name: raw
  #   schema: staging
  #   tables:
  #     - name: users
  #       identifier: seed_users
