name: cache_demo
version: "0.1"

vars: {}

models:
  storage:
    stg_users.ff:
      path: ".local/spark/stg_users"
    stg_orders.ff:
      path: ".local/spark/stg_orders"
    mart_user_orders.ff:
      path: ".local/spark/mart_user_orders"
    py_constants:
      path: ".local/spark/py_constants"
    http_users:
      path: ".local/spark/http_users"

seeds:
  storage:
    seed_users:
      path: ".local/spark/seed_users"
    seed_orders:
      path: ".local/spark/seed_orders"

tests:
  - type: row_count_between
    table: stg_users
    min_rows: 3
    tags: [batch]
