name: cache_demo
version: "0.1"

vars: {}

models: {}

seeds:
  storage:
    seed_users:
      path: ".local/spark/seed_users"
    seed_orders:
      path: ".local/spark/seed_orders"

tests:
  - type: row_count_between
    table: stg_users
    min_rows: 3
    tags: [batch]
