{{ config(
    materialized='table',
    tags=['example:macros_demo', 'scope:common', 'engine:duckdb', 'engine:postgres', 'engine:databricks_spark']
) }}

with u as (
  select * from {{ ref('stg_users.ff') }}
),
labels as (
  -- Tiny lookup generated by Python render macro
  select * from (values {{ csv_values(
      [
        {"domain":"example.com", "label":"internal"},
        {"domain":"gmail.com",   "label":"consumer"},
      ],
      ["domain","label"]
  ) }}) as t(domain, label)
)
select
  u.user_id,
  u.email,
  u.email_domain,
  u.country,
  l.label as user_segment
from u
left join labels l on l.domain = u.email_domain;
