name: example_postgres
version: 0.1
models_dir: models

docs:
  dag_dir: site/dag

tests:
  - type: not_null
    table: users
    column: id
    tags: [batch]
  - type: unique
    table: users
    column: id
    tags: [batch]

  # Cross-table reconciliations (FF-310)
  - type: reconcile_equal
    name: orders_count_equals_mart
    tags: [reconcile]
    left:  { table: orders,               expr: "count(*)" }
    right: { table: mart_orders_enriched, expr: "count(*)" }

  - type: reconcile_coverage
    name: orders_fully_covered_in_mart
    tags: [reconcile]
    source: { table: orders,               key: "order_id" }
    target: { table: mart_orders_enriched, key: "order_id" }
