name: materializations_demo
version: "0.1"

vars: {}

models: {}

seeds: {}

tests:
  # Simple sanity tests; add more if you like
  - type: not_null
    table: dim_customers
    column: customer_id
    tags: [batch, example:materializations_demo]
  - type: row_count_between
    table: dim_customers
    min_rows: 1
    tags: [batch, example:materializations_demo]
  - type: not_null
    table: fct_orders_inc
    column: order_id
    tags: [batch, example:materializations_demo]
