default:
  dev:
    engine: "{{ env('FF_ENGINE' }}"

    # Router variable binds "api_users_model" to the *canonical* model name
    # We keep the same value for all engines here (api_users_http), but it could differ
    # (e.g. "api_users_requests" or a parquet loader) per engine in real projects.
    vars:
      api_users_model: "api_users_http"

    duckdb:
      path: "{{ env('FF_DUCKDB_PATH') }}"

    postgres:
      # Safe default DSN for local dev; override via FF_PG_DSN in CI/Prod
      dsn: "{{ env('FF_PG_DSN') }}"
      db_schema: "{{ env('FF_PG_SCHEMA') }}"

    databricks_spark:
      master: "{{ env('FF_SPARK_MASTER') }}"
      app_name: "api_demo"
