name: duckdb_api_demo
version: "0.1"

vars: {}

models:
  storage:
    users:
      path: ".local/spark/users"
      format: parquet
    api_users_http:
      path: ".local/spark/api_users_http"
      format: parquet
    api_users_requests:
      path: ".local/spark/api_users_requests"
      format: parquet
    mart_users_join.ff:
      path: ".local/spark/mart_users_join"
      format: parquet

seeds:
  storage:
    seed_users:
      path: ".local/spark/seed_users"
      format: parquet

tests:
  - type: not_null
    table: mart_users_join
    column: user_id
    tags: [batch]
  - type: row_count_between
    table: mart_users_join
    min_rows: 3
    max_rows: 3
    tags: [batch]
