name: duckdb_api_demo
version: "0.1"

vars: {}

models: {}

seeds:
  storage:
    seed_users:
      path: ".local/spark/seed_users"
      format: parquet

tests:
  - type: not_null
    table: mart_users_join
    column: user_id
    tags: [batch]
  - type: row_count_between
    table: mart_users_join
    min_rows: 3
    max_rows: 3
    tags: [batch]
