name: duckdb_env_matrix_demo
version: "0.1"

vars: {}

tests:
  # Batch‑Tabellen
  - type: accepted_values
    table: env_vars
    column: ff_engine
    values: [duckdb]
    tags: [batch]

  - type: row_count_between
    table: users
    min_rows: 3
    max_rows: 3
    tags: [batch]
