name: incremental_demo
version: "0.1"

vars: {}

models:
  incremental:
    fct_events_sql_inline.ff:
      unique_key: "event_id"

    fct_events_sql_yaml.ff:
      unique_key: "event_id"

    fct_events_sql_yaml.ff:
      unique_key: "event_id"               # top-level shortcut
      incremental:
        enabled: true
        updated_at_column: "updated_at"

    fct_events_sql_inline_delta.ff:
      unique_key: "event_id"

seeds: {}

tests:
  - type: not_null
    table: fct_events_sql_inline
    column: event_id
    tags: [incremental]

  - type: not_null
    table: fct_events_sql_yaml
    column: event_id
    tags: [incremental]

  - type: not_null
    table: fct_events_py_incremental
    column: event_id
    tags: [incremental]
