# Connection profiles for the basic demo.
# Populate environment variables as shown in the accompanying .env.dev_* files.

dev_duckdb:
  engine: duckdb
  duckdb:
    path: "{{ env('FF_DUCKDB_PATH', '.local/basic_demo.duckdb') }}"

dev_duckdb_utest:
  engine: duckdb          # must match
  duckdb:
    # completely separate DB just for utests
    path: "{{ env('FF_DUCKDB_UTEST_PATH', ':memory:') }}"

dev_postgres:
  engine: postgres
  postgres:
    dsn: "{{ env('FF_PG_DSN') }}"
    db_schema: "{{ env('FF_PG_SCHEMA', 'public') }}"

dev_postgres_utest:
  engine: postgres        # same engine
  postgres:
    # just override schema, keep same DSN
    db_schema: "{{ env('FF_PG_UTEST_SCHEMA', 'basic_demo_utest') }}"

dev_databricks:
  engine: databricks_spark
  databricks_spark:
    master: "{{ env('FF_SPARK_MASTER', 'local[*]') }}"
    app_name: "{{ env('FF_SPARK_APP_NAME', 'basic_demo') }}"
    warehouse_dir: "{{ project_dir() }}/.local/spark_warehouse"
    database: "{{ env('FF_DBR_DATABASE', 'basic_demo') }}"
    extra_conf:
      spark.sql.statistics.fallBackToHdfs: true
      spark.sql.shuffle.partitions: "{{ env('SPARK_SQL_SHUFFLE_PARTITIONS', '8') }}"
      spark.driver.extraJavaOptions: >
        -Dderby.stream.error.file={{ project_dir() }}/.local/derby.log
        -Dderby.system.home={{ project_dir() }}/.local/derby_home

dev_databricks_utest:
  engine: databricks_spark
  databricks_spark:
    database: "{{ env('FF_DBR_DATABASE', 'basic_demo_utest') }}"

dev_bigquery_bigframes:
  engine: bigquery
  bigquery:
    project: "{{ env('FF_BQ_PROJECT') }}"
    dataset: "{{ env('FF_BQ_DATASET', 'basic_demo') }}"
    location: "{{ env('FF_BQ_LOCATION', 'EU') }}"
    use_bigframes: true
    allow_create_dataset: true

dev_bigquery_bigframes_utest:
  engine: bigquery
  bigquery:
    # override only dataset
    dataset: "{{ env('FF_BQ_UTEST_DATASET', 'basic_demo_utest') }}"

dev_bigquery_pandas:
  engine: bigquery
  bigquery:
    project: "{{ env('FF_BQ_PROJECT') }}"
    dataset: "{{ env('FF_BQ_DATASET', 'basic_demo') }}"
    location: "{{ env('FF_BQ_LOCATION', 'EU') }}"
    use_bigframes: false
    allow_create_dataset: true

dev_bigquery_pandas_utest:
  engine: bigquery
  bigquery:
    # override only dataset
    dataset: "{{ env('FF_BQ_UTEST_DATASET', 'basic_demo_utest') }}"

dev_snowflake:
  engine: snowflake_snowpark
  snowflake_snowpark:
    account: "{{ env('FF_SF_ACCOUNT') }}"
    user: "{{ env('FF_SF_USER') }}"
    password: "{{ env('FF_SF_PASSWORD') }}"
    warehouse: "{{ env('FF_SF_WAREHOUSE', 'COMPUTE_WH') }}"
    database: "{{ env('FF_SF_DATABASE', 'EXAMPLE_DEMO') }}"
    schema: "{{ env('FF_SF_SCHEMA', 'BASIC_DEMO') }}"
    role: "{{ env('FF_SF_ROLE', '') }}"
    allow_create_schema: true

dev_snowflake_utest:
  engine: snowflake_snowpark
  snowflake_snowpark:
    schema: "{{ env('FF_SF_UTEST_SCHEMA', 'BASIC_DEMO_UTEST') }}"
